### ISSUE TITLE
コンパイルエラーについて

### ISSUE THREAD

**Issue by mizushima1226** [kojioki50/memo-story#1]
こちらのコンパイルエラー再現しますでしょうか？
いくつかのファイルでエラーを発見しました

<img width="1512" alt="スクリーンショット 2022-04-17 13 44 21" src="https://user-images.githubusercontent.com/47247884/163700793-ad81cf1b-2674-4015-983f-f95ec19e352a.png">

**Comment by kojioki50** [comment]
<img width="1440" alt="スクリーンショット 2022-04-17 14 40 11" src="https://user-images.githubusercontent.com/86749873/163702174-24478679-2f1c-45cc-9e51-88566b56a33a.png">

こちらではエラーで出てませんがなんかインストールが足りてないからエラー出ないんですかね？

**Comment by mizushima1226** [comment]
#2 の対応で解消されたみたいですね👀
このissueはcloseします〜
