### ISSUE TITLE
RegisterMemoなどのラジオボタンが効かない件について

### ISSUE THREAD

**Issue by mizushima1226** [kojioki50/memo-story#2]
タイトルの通りです。
噂話・悪口のラジオボタンが反応しないようです👀

チェックボックスのスタイルも崩れている？？

**Comment by kojioki50** [comment]
こちらは拡大してみたらめちゃ小さく機能はしてるんですがスタイルが崩れていてどう直したいいのかわからず放置してしまっていました。サイズを変えてもradiobuttonの大きさがわからずstorybookの時だけ崩れてしまうのでいまいちわからない状況です。

**Comment by kojioki50** [comment]
npm i @chakra-ui/storybook-addon

こちらをインストールしていなかったためにいろんなところのスタイルがちゃんとなっていませんでした。
修正しました。

**Comment by mizushima1226** [comment]
修正確認できました〜
Modal/BasicとRegisterMemo/Basicではラジオボタンの色が異なってますが意図通りでしょうか？

あと、Modal/Basic側のラジオボタンだけ編集可能となっていますが、問題ありませんでしょうか？
他の入力は制御されてコンポーネントのようで入力を受け付けなくなっています👀

**Comment by kojioki50** [comment]
色が異なってるはミスです修正しましたすいません。

Modal/Basicはそれで問題ないつもりで提出しましたが、改めてみてみるとやっぱり一つだけ編集は良くないなと思って
全て編集できるように変更しました。

**Comment by mizushima1226** [comment]
修正内容確認できました！！
issueはcloseします〜
